### ISSUE TITLE
Coverage not collected

### ISSUE THREAD

**Issue by agross** [codecov/example-typescript-vscode-extension#1]
Hi @nixel2007,

Thank you for posting an answer to my question on the VS Code issue tracker. I tried your example from this repo and it works for me.

Unfortunately I was not able to get it working for my VS Code extension. I suspect the require hook runs too late because it is not called for the extension itself. I added some `console.log` statements to the `matchFn` but only files in `node_modules` show up.

Any ideas what I'm missing?

[Here's the repo](https://github.com/agross/code-settings-sync/commit/0194dfb4de64fdf6d1beb7adbd605efff6fe3953) including your `test/index.ts`.

Many thanks from a JS/TS/VSCode noob! :)

**Comment by nixel2007** [comment]
@agross hi there. I'll try to check you repo, but only on Tuesday. Sorry for a delay

**Comment by agross** [comment]
NP, I'll attempt to fix myself in the meantime. Looking forward to your feedback!

**Comment by agross** [comment]
Hey @nixel2007, did you have time to take a look?

**Comment by nixel2007** [comment]
Oh god, sorry, I forgot about everything. I'll make a calendar entry to handle this.

**Comment by agross** [comment]
Thanks! Please let me know when you had the opportunity to take a look.

**Comment by nixel2007** [comment]
@agross i've found the problem. It's a VSCode specific, I'm trying to find a workaround

**Comment by nixel2007** [comment]
@agross okey, i have a goot news and a bad news.
Good news - i've got a coverage result:
![image](https://user-images.githubusercontent.com/1132840/32786122-2bd15dc0-c964-11e7-8df2-19919e97cc4d.png)

Bad news - to get this i've turned off `*` activation event. My digging led me to some really strange behavior. If your extensions activated with `*` instrumenting of extension.js won't work and provide any coverage info other than compilation of module (all imports and func definitions). **But** if you remove the `*` event and activate your extension with some command listed in activation events list or via vscode.extension.getExtension().activate - then everything works.

**Comment by nixel2007** [comment]
You could try to find some other (not `*`) activation events that will work with coverage AND activate an extension early.

**Comment by agross** [comment]
Many thanks for your time invested in the research! Unfortunately any other activation than `*` will not work for this extension as it needs to be activated once VS Code starts up. But I think I can work from there by extracting the code from `extension.ts` into separate classes and test them in isolation.
